name: inventorypro
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  #sdk: '>=2.12.0 <3.0.0'
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+4
  firebase_core: ^2.7.0
  firebase_auth: ^4.5.0
  firebase_database: ^10.4.8
  firebase_storage: ^11.6.11
  cupertino_icons: ^1.0.6
  animate_do: ^3.1.2
  flutter_local_notifications: ^9.1.6
  
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.0.0
  intl: ^0.17.0
  path_provider: ^2.0.9
  equatable: ^2.0.3
  rive: ^0.12.4

  fluttertoast: ^8.0.7
  uuid: ^4.4.0
  #flushbar: ^1.10.4

  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  

 
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/inven.jpg
    - assets/images/agregar.png
    - assets/images/compras.png
    - assets/images/clientes.png
    - assets/images/estadistica.jpg
    - assets/images/caja.png
    - assets/images/carpeta.png
    - assets/images/inventario.png
    - assets/images/transaccion.png
    - assets/images/cont.png


fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Black.ttf