// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCILcoGUPOW_YvSDdAL1-AyTu6n_oFfakA',
    appId: '1:531161998897:web:5aa33d983bd66b7c699710',
    messagingSenderId: '531161998897',
    projectId: 'inventorypro-5911f',
    authDomain: 'inventorypro-5911f.firebaseapp.com',
    storageBucket: 'inventorypro-5911f.appspot.com',
    measurementId: 'G-2GBJZKX69Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVqpRhCcw_JB4jEnSD9COiFUPkV0QwQxk',
    appId: '1:531161998897:android:57923f1b9fa5081c699710',
    messagingSenderId: '531161998897',
    projectId: 'inventorypro-5911f',
    storageBucket: 'inventorypro-5911f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAROf63Ce9CeCf53zTE7GDM2T-C6nR9Oos',
    appId: '1:531161998897:ios:545d72ed279a76eb699710',
    messagingSenderId: '531161998897',
    projectId: 'inventorypro-5911f',
    storageBucket: 'inventorypro-5911f.appspot.com',
    iosBundleId: 'com.example.inventorypro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAROf63Ce9CeCf53zTE7GDM2T-C6nR9Oos',
    appId: '1:531161998897:ios:ded5901487686f3d699710',
    messagingSenderId: '531161998897',
    projectId: 'inventorypro-5911f',
    storageBucket: 'inventorypro-5911f.appspot.com',
    iosBundleId: 'com.example.inventorypro.RunnerTests',
  );
}
